import assert from 'node:assert/strict';
import { OBTER_SETE_PERGUNTAS_ESTRATEGICAS, CRIAR_DIAGNOSTICO_COMPLETO, FILTRO_COMPLETO, GERAR_SENSORIAMENTO_MERCADO } from '../src/servicos/servicoDiagnostico';
import { IDENTIFICAR_CATEGORIA_VISUAL } from '../src/servicos/servicoCategoriasVisuais';
import { MONTAR_PROMPT_VISUAL } from '../src/servicos/servicoContextoVisual';
import { GERAR_MOCK_CAMPANHA_MODULO_3 } from '../src/servicos/servicoIA';
import { GERAR_LEMBRETE_ICS } from '../src/servicos/servicoAgenda';
import { VALIDAR_ESTRATEGIAS_GEMINI } from '../src/servicos/servicoGemini';
import { GERAR_ESTRATEGIA_TRIPLA } from '../src/servicos/servicoIA';

const perguntas = OBTER_SETE_PERGUNTAS_ESTRATEGICAS('Salão de cabeleireiro');
assert.equal(perguntas.length, 7);
assert.ok(!perguntas[6].opcoes[0].rotulo.includes('estoque'));
assert.equal(IDENTIFICAR_CATEGORIA_VISUAL('Salão de cabeleireiro'), 'salao');
assert.equal(IDENTIFICAR_CATEGORIA_VISUAL('Varejo de roupas'), 'moda');
assert.equal(IDENTIFICAR_CATEGORIA_VISUAL('Varejo'), 'generico');
assert.equal(IDENTIFICAR_CATEGORIA_VISUAL('Salão de cabeleireiro', 'Café Hair'), 'salao');
assert.equal(IDENTIFICAR_CATEGORIA_VISUAL('Clínica estética'), 'estetica');
assert.equal(FILTRO_COMPLETO({ 1: { valores: ['outros'], textoOutros: ' ' } }), false);
const respostas = Object.fromEntries(perguntas.map(p => [p.id, { valores: [p.opcoes[0].valor] }]));
assert.equal(FILTRO_COMPLETO(respostas), true);
const diag = CRIAR_DIAGNOSTICO_COMPLETO('Hair Blue', 'Salão de cabeleireiro', 'Presencial', 'Local', respostas);
assert.equal(diag.categoriaModelo.quadrante, 3);
assert.equal(VALIDAR_ESTRATEGIAS_GEMINI(null), false);
assert.equal(VALIDAR_ESTRATEGIAS_GEMINI({ estrategiaBase: {} }), false);
assert.equal(VALIDAR_ESTRATEGIAS_GEMINI(GERAR_ESTRATEGIA_TRIPLA(diag)), true);
assert.ok(GERAR_ESTRATEGIA_TRIPLA(diag).estrategiaBase.descricao.includes('Hipótese'));
assert.deepEqual(GERAR_SENSORIAMENTO_MERCADO('Salão', 'Local').casosDeSucessoAncorados, []);
const prompt = MONTAR_PROMPT_VISUAL(diag, GERAR_MOCK_CAMPANHA_MODULO_3(diag), 'pixel art');
assert.ok(prompt.includes('Hair Blue') && prompt.includes('Salão de cabeleireiro') && prompt.includes('pixel art'));
const ics = GERAR_LEMBRETE_ICS({ id:'test', diagnosticoId:diag.id, titulo:'Post; teste', dataHorario:'2026-09-10T12:00:00-03:00', canal:'Instagram Feed', status:'agendado', copy:'Linha 1\nLinha 2', hashtags:[], criadoEm:diag.dataCriacao });
assert.ok(ics.includes('DTSTART:20260910T150000Z'));
assert.ok(ics.includes('TRIGGER:-PT30M'));
assert.ok(ics.includes('SUMMARY:Post\\; teste'));
console.log('Regressões verificadas: setor, questionário, diagnóstico, contexto visual e lembrete.');
